In [30]:
import numpy as np

In [31]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])


In [32]:
a.ndim

2

In [33]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

№1.Найдите среднее значение по каждому признаку, используя метод mean массива Numpy

In [35]:
mean_a = a.mean(axis=0)

In [36]:
mean_a

array([2. , 8.4])

№2. Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a

In [37]:
a_centered = a - mean_a

In [38]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

№3. Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений (их у нас 5)

In [39]:
a_centered_sp = a_centered[:, 0] @ a_centered [:, 1]

In [40]:
a_centered_sp

8.0

In [42]:
a.shape[0]

5

In [43]:
a_centered_sp/(a.shape[0] - 1)

2.0

№4. В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. 

In [50]:
cov_a = np.cov(a.T)[0][1]
cov_a

2.0