In [5]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
from pylab import rcParams
%config InlineBackend.figure_format = 'svg'
from scipy.stats import mode
import warnings
warnings.filterwarnings('ignore')

№1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [6]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

№2.Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [7]:
a1 = a.reshape (6,2)
a2 = a.reshape (4,3)
a3 = a.reshape (3,4)
a4 = a.reshape (12,1)
a5 = a.reshape (1,12)
print("Массив a1:", a1)
print("Массив a2:", a2)
print("Массив a3:", a3)
print("Массив a4:", a4)
print("Массив a5:", a5)

Массив a1: [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Массив a2: [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Массив a3: [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Массив a4: [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
Массив a5: [[12 13 14 15 16 17 18 19 20 21 22 23]]


№3.Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [8]:
a1 = a.reshape (6,-2)
a2 = a.reshape (-4,3)
a3 = a.reshape (3,-4)
a4 = a.reshape (12,-1)
a5 = a.reshape (-1,12)
print("Массив a1:", a1)
print("Массив a2:", a2)
print("Массив a3:", a3)
print("Массив a4:", a4)
print("Массив a5:", a5)

Массив a1: [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Массив a2: [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Массив a3: [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Массив a4: [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
Массив a5: [[12 13 14 15 16 17 18 19 20 21 22 23]]


№4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [9]:
a.shape == a4.shape

False

In [10]:
a.shape

(12,)

In [11]:
a4.shape

(12, 1)

In [12]:
a4.dtype

dtype('int32')

Массив а4, состоящий из 1 стоблца и 12 строк, нельзя назвать одномерным, тк по размерности он имеет номер строки, а также выводится в двойных [].

№5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [13]:
c = np.random.rand(3,4)
print(c)

[[0.15883493 0.55528594 0.62497785 0.31357729]
 [0.28583315 0.208203   0.19866194 0.79049338]
 [0.34945449 0.35875818 0.05437792 0.92974946]]


In [14]:
c.size

12

In [15]:
b = c.flatten()
b.size

12

In [16]:
print(b)

[0.15883493 0.55528594 0.62497785 0.31357729 0.28583315 0.208203
 0.19866194 0.79049338 0.34945449 0.35875818 0.05437792 0.92974946]


№6.Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [17]:
a = np.arange(20,0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

№7.Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [18]:
b = np.arange(20, 1,-2)
b = np.reshape(b,(1,10))
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [19]:
a.shape

(10,)

In [20]:
b.shape

(1, 10)

разница между а и b в том, что а - одномерный массив, а b -  двумерный массив. смотрим на размерность(функция - .shape)

№8.Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [21]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [22]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
v.size

10

№9.Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [25]:
a = np.arange(0,12)
a1 = a.reshape((4,3))
At = a1.T
B= np.dot(a1,At)
#inv_B= np.linalg.inv(B)
print(a1)
print(At)
print(B)
print("определитель B равен: ",np.linalg.det(B))
#
# матрица В не имеет обратной матрицы из за того что она сингулярная, определитель равен 0
#

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
определитель B равен:  0.0


№10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42

In [26]:
import random

random.seed(42)
print(random.random())


0.6394267984578837


№11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [27]:
t = np.random.randint(0,16, 16)
t

array([ 1, 12,  0,  7, 11, 11, 13,  6,  4,  1,  6,  5,  4,  7, 10,  6])

№12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [34]:
C = t.reshape((4,4))
print(C)
print(B)
D=B+C*10
print("D= ",D)

print(np.linalg.det(D))
print("ранг D =", np.linalg.matrix_rank(D))
D_inv=np.linalg.inv(D)
print('Обратная матрица:',D_inv)


[[ 1 12  0  7]
 [11 11 13  6]
 [ 4  1  6  5]
 [ 4  7 10  6]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
D=  [[ 15 134  23 102]
 [124 160 216 182]
 [ 63  96 209 262]
 [ 72 192 312 362]]
163378000.00000018
ранг D = 4
Обратная матрица: [[ 0.00326507  0.00915533  0.01959823 -0.0197073 ]
 [ 0.00469757  0.00176315 -0.01193527  0.00642816]
 [-0.00988921  0.00142455 -0.01628763  0.01385854]
 [ 0.00538236 -0.00398389  0.01647027 -0.00867167]]


№13.Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [35]:
D_inv=np.where(D_inv<0, 0,1)
print('D_inv:', D_inv)
E=np.where(D_inv==1, B, C)
print('E:', E)


D_inv: [[1 1 1 0]
 [1 1 0 1]
 [0 1 0 1]
 [1 0 1 0]]
E: [[  5  14  23   7]
 [ 14  50  13 122]
 [  4  86   6 212]
 [ 32   7 212   6]]
